spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/static , file:C://Users/Ning/BALF/image_output

  datasource:
    url: jdbc:mysql://localhost:3306/balf?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver #引入pom后这个有效


  servlet:
    multipart: # # 修改文件上传的大小限制
      max-request-size: 1024MB   # 运行请求传递文件大小最大为1024MB
      max-file-size: 1024MB       # 运行服务器可以处理的最大文件大小1024MB


# 配置mybatis规则、使用MyBatisPlus则此项配置无效
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:  # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true

file:
  upload:
    dir: C://Users/Ning/BALF/upload

#project:
#  static:
#    resources:
#      static-locations: classpath:/, C://Users/L/Desktop/BALF/image_output/
#      resourceLocations: classpath:/, C://Users/L/Desktop/BALF/image_output/
#    add-mappings: true
#    cache:
#      period: 11000

#server:
#  servlet:
##    context-path: /world
#    context-path:



#spring:
#  profiles:
#    include: [data-dev]
#  static: #静态文件资源
#    template-page-path: classpath:/templates/page/ #加载模版路径
#    resources:
#      #访问静态资源规则，可配置多个以','或'，'隔离
#      - pathPatterns: /static/**,/chengyi/**
#        #静态资源文件位置，可配置多个以','或'，'隔离
#        resourceLocations: classpath:/templates/static/,file:${case.outPath},classpath:/templates/chengyi/,file:${case.chengyi}